### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by iog3** [shpasser/GaeSupportL5#3] opened 2015-02-27 12:12 UTC
Although this may be nothing to do with your code, do you have any tips for speed on gae?
I have a vps and gae running the same code and the vps averages 200ms response times, where as app engine averages 1000ms to 2500ms! And doesn't seem very consistent.

I've tried route caching and artisan optimize but they just my the vps speed up even more, no change to gae even on the F4 instances.

Speed on GAE:
![Image of Gae](http://i.imgur.com/Tks2puU.png)

Speed on Linode UK Server
![Image of Linode](http://i.imgur.com/M6A8Dkm.png)

Regards,
Adam

**Comment by shpasser** [comment] 2015-02-27 14:48
I haven't tried yet to profile any app on GAE, but it can be interesting.

I do not have any tips right now, but I may have some in couple of weeks. 

As for the cause of the high latency I would try to profile the parts of code related to BLADE compilation and reuse of already compiled views. I'm not 100% sure, but the problem might be the use of GCS buckets for storing the compiled views. On the other hand these GCS buckets are the only means of writable storage on GAE I know of currently. 

I'm willing to start digging, please keep me posted on your progress too.

Best,

Ron.

**Comment by shpasser** [comment] 2015-02-28 18:29
BTW, Linode is advertised as SSD based, there is a very big difference between SSD and regular based storage.

**Comment by iog3** [comment] 2015-03-03 09:26
I'm making a little benchmarking tool for L5 and I'll get it running on a few different hosts so we can see the results.

I've got;
App Engine
Azure VM
Linode VM
DigitalOcean VM
Rackspace VM

Don't have a AWS account though.

Adam

**Comment by shpasser** [comment] 2015-03-03 11:35
Thanks for the update, please let me know how it goes.

I tried different cache related changes, no results till now.

**Comment by mattbucci** [comment] 2015-03-03 17:14
I wonder if maybe we could override the view engine to use memcache if that really is the issue

**Comment by shpasser** [comment] 2015-03-03 18:24
Sounds interesting, it looks like will have to override some code related to compiled view storage and retrieval. The key for memcache can be as returned by `Compiler::getCompiledPath()`. Additionally will have to replace `include $__path;` with something like `eval(stringFromMemcache)` in `PhpCompiler::evaluatePath()` if I'm getting it right.

**Comment by shpasser** [comment] 2015-03-03 18:29
There are other functions to be taken care of like `Compiler:isExpired`, meaning everything relying on use of filesystem has to be overridden.

**Comment by mattbucci** [comment] 2015-03-03 22:03
So if all we're concerned about is performance I have a good idea of how to speed this up by just overriding View::render. I recently just did this for our platform in order to process blade templates as a dom document and switch links out for CDN links. 

I'm just not sure how to work this into your package, within view render all we need to do is if memcache set as cache engine
$contents Cache::get($this->path)
if(!empty($contents)) {
    return $contents
}
do our normal call to the GAE bucket
Cache::put($this->path, $this->contents);


    <?php
    namespace Genentech\Helpers\Cdn;
    
    use Closure;
    use Illuminate\View\View;
    
    class CdnView extends View
    {
    
        public function render(Closure $callback = null)
        {
            $contents = $this->renderContents();
            // only CDNify assets if on final pass of rendering
            if ($this->factory->doneRendering()) {
                $contents = CdnHelper::convertContentForCDN($contents);
            }
    
            $response = isset($callback) ? $callback($this, $contents) : null;
    
            // Once we have the contents of the view, we will flush the sections if we are
            // done rendering all views so that there is nothing left hanging over when
            // anothoer view is rendered in the future by the application developers.
            $this->factory->flushSectionsIfDoneRendering();
    
            return $response ?: $contents;
        }
    
    }


    <?php
    namespace Genentech\Helpers\Cdn;
    
    use Illuminate\View\Factory as Factory;
    
    class CdnViewFactory extends Factory
    {
    
        public function make($view, $data = array(), $mergeData = array())
        {
            if (isset($this->aliases[$view])) {
                $view = $this->aliases[$view];
            }
    
            $view = $this->normalizeName($view);
    
            $path = $this->finder->find($view);
    
            $data = array_merge($mergeData, $this->parseData($data));
    
            $this->callCreator($view = new CdnView($this, $this->getEngineFromPath($path), $view, $path, $data));
    
            return $view;
        }
    
    }


    <?php
    namespace Genentech\Gene\Frontend\Providers;
    
    use Genentech\Helpers\Cdn\CdnViewFactory;
    use Illuminate\Support\ServiceProvider;
    
    final class CdnServiceProvider extends ServiceProvider
    {
    
        public function register()
        {
            $this->app->extend('view', function () {
                $app = app();
                // Next we need to grab the engine resolver instance that will be used by the
                // environment. The resolver will be used by an environment to get each of
                // the various engine implementations such as plain PHP or Blade engine.
                $resolver = $app['view.engine.resolver'];
    
                $finder = $app['view.finder'];
    
                $env = new CdnViewFactory($resolver, $finder, $app['events']);
    
                // We will also set the container instance on this view environment since the
                // view composers may be classes registered in the container, which allows
                // for great testable, flexible composers for the application developer.
                $env->setContainer($app);
    
                $env->share('app', $app);
    
                return $env;
            });
        }
    }

**Comment by mattbucci** [comment] 2015-03-03 22:05
I could extract this out to a package if you want?

**Comment by mattbucci** [comment] 2015-03-03 22:57
https://github.com/letsrtfm/laravel5-memcache-views 

Completely untested, so keep that in mind

**Comment by mattbucci** [comment] 2015-03-04 02:59
I noticed a significant speed bump, views are now instant.
![screen shot 2015-03-03 at 6 49 17 pm](https://cloud.githubusercontent.com/assets/3284147/6477255/15bf1204-c1d6-11e4-84cd-444f3cb76c41.jpg)

however, we're still fetching resources from our cloud bucket on every request, if you want that sub 200ms response you're going to have to override the adapter in general like Ron proposed
![screen shot 2015-03-03 at 6 47 59 pm](https://cloud.githubusercontent.com/assets/3284147/6477259/1ea11a0c-c1d6-11e4-9f36-f6a1b5c9a9ce.jpg)

Running a trace reveals the following call stream to GAE

404 HEAD https://genentechlunchclub.storage.googleapis.com/storage 

200 GET https://genentechlunchclub.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage

404 GET https://genentechlunchclub.storage.googleapis.com/storage/framework/config.php

200 GET https://genentechlunchclub.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage%2Fframework%2Fconfig.php

404 HEAD https://genentechlunchclub.storage.googleapis.com/storage/framework/views

200 GET https://genentechlunchclub.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage%2Fframework%2Fviews

200 HEAD https://genentechlunchclub.storage.googleapis.com/storage/framework/services.json

304 GET https://genentechlunchclub.storage.googleapis.com/storage/framework/services.json

404 HEAD https://genentechlunchclub.storage.googleapis.com/storage/framework/routes.php

200 GET https://genentechlunchclub.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage%2Fframework%2Froutes.php

404 HEAD https://genentechlunchclub.storage.googleapis.com/storage/framework/down

200 GET https://genentechlunchclub.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage%2Fframework%2Fdown

It's 50ms a request......

**Comment by danielmalone** [comment] 2015-03-04 05:46
I am also experiencing a lag on Google App Engine of about 1200ms. Every page request. I've tried for a few weeks to get it to work, but couldn't figure it out. I would really appreciate a solution. Thank you so much for this!

**Comment by mattbucci** [comment] 2015-03-04 07:24
bad news is i overrode the wrong thing in my package, the solution posted above only works if you're returning the same data every time. 

An alternative would be to override the Compiler like so

    protected function evaluatePath($__path, $__data)
	{
		$obLevel = ob_get_level();

		ob_start();

		extract($__data);

		// We'll evaluate the contents of the view inside a try/catch block so we can
		// flush out any stray output that might get out before an error occurs or
		// an exception is thrown. This prevents any partial views from leaking.
		try
		{
			if ($this->runningOnGAE()) {
				if (\Cache::has($__path))
				{
					var_dump('hit');
					$code = \Cache::get($__path);
				} else {
					$code = file_get_contents($__path);
					\Cache::forever($__path, $code);
				}
				eval("?>" . $code . "<?php ");
			} else {
				include $__path;
			}
		}
		catch (Exception $e)
		{
			$this->handleViewException($e, $obLevel);
		}

		return ltrim(ob_get_clean());
	}

But I'm looking into if it's possible to just override the native file system instead in a reliable way, that way all the HEAD calls get cached as well. 

I originally wanted to just pass a flysystem caching adapter, but the Native file system not passed as an interface

**Comment by shpasser** [comment] 2015-03-04 08:17
WOW! Looks like lots of things happened since I went to sleep. Started working on GCS storage replacement. Will let you know when I have something I can show.

**Comment by iog3** [comment] 2015-03-04 11:15
Sorry I can't write much code till the weekend! 
I think we need to bear in mind the GAE Memcache limits, I'm not sure if they are hard limits or not

https://cloud.google.com/appengine/docs/adminconsole/memcache

If higher traffic sites have larger views it might hit the ops/s limit.
What classes as an op? I assume read and write not just writes?

Adam

**Comment by mattbucci** [comment] 2015-03-04 21:02
"For example, an app configured for 5GB of cache could reach 50,000 small-item memcache operations/sec. Achieving this level requires a good distribution of load across the memcache keyspace (see Best practices below)."

From the docs. this makes me think the op/s is just a performance guarantee. I've updated my package to override the view engine instead so it only caches the unevaluated php, not the full html. It helps, but like i said, without a way to cache the routes.php, config.php, etc I've seen pretty terrible performance still.

I tried overwriting the native storage engine, but in my profiles I was still incurring a cost for calls to HEAD.....I overwrote the get and exists calls, I'm not sure what I was missing. 

I'm also not worrying about expiring items as of now, meaning you'll need to flush memcache when you deploy. So far though it's not been promising.

**Comment by shpasser** [comment] 2015-03-05 01:14
You mean there are still HEAD requests towards the GCS? Then I don't really understand the approach of overwriting the native storage you are using. Please clarify on your approach, so I could try and help you.
As I wrote before I replaced the GCS with memcached based file system of my own. It works, I can see a very significant performance boost. It needs some more polishing and will have to find the right way to integrate it with Laravel.

**Comment by mattbucci** [comment] 2015-03-05 01:15
I'll wait to see yours, sounds great!

**Comment by shpasser** [comment] 2015-03-05 01:35
In my approach I'm using PHP's stream wrapper to implement the filesystem. I still have to do some work on polishing the directory support, but it works even without it. The issues regarding cached routes and configuration are still relevant, but solvable by reading them from read-only

**Comment by shpasser** [comment] 2015-03-07 23:18
Still working on the filesystem, had to rethink some of the concepts, please stay tuned.

**Comment by shpasser** [comment] 2015-03-09 20:23
The filesystem is under tests now. Need to understand how to generate cached `config.php` with proper paths(the ones used while running on GAE).

**Comment by jjosephs** [comment] 2015-03-23 19:55
Any update on this issue guys? I would help if I could.

**Comment by shpasser** [comment] 2015-03-25 19:52
I'm in the middle of the last preparations before pushing an update to the master branch. Some of the features will be `experimental` please get ready for testing the update with your apps.

**Comment by iog3** [comment] 2015-03-26 08:57
Why not put it in a branch for testing?

**Comment by shpasser** [comment] 2015-03-26 22:04
Most of the features are tested, the others are nearly fully tested.  By 'experimental' I meant that a more extensive testing with many use cases should be done in order to understand if it is really something that can be of use. I do not think that we need a testing branch for that kind of features, but it seems to be a very good idea for the upcoming features and extensions.

**Comment by mattbucci** [comment] 2015-03-31 18:31
Any updates?

**Comment by shpasser** [comment] 2015-04-02 05:18
Just a couple more days, I was very busy lately.

**Comment by mattbucci** [comment] 2015-04-02 06:47
no problem, hope all is well.

**Comment by shpasser** [comment] 2015-04-07 19:23
Just pushed it to the master branch. I tested the new features in couple of my projects and they seem to work as expected. In order to eliminate GSC usage remove `FILESYSTEM=gae` from your `.env.production` file if you do not use it.

**Comment by mattbucci** [comment] 2015-04-08 22:46
Awesome, thanks for your hard work. I'll integrate it into my app and let you know if anything doesn't act as expected!

**Comment by ardalann** [comment] 2015-04-10 07:27
Thank you @shpasser for this great work! 
I wanted to test the new version to see if the speed issue is fixed. I pulled the "dev-master" version using composer and when I tried to set it up using gae:setup command, I got this error:

```
Created the ".env.production" file.
Created the ".env.local" file.
Replaced the application class in "bootstrap/app.php".
Replaced the service providers in "config/app.php".
Set the log handler in "config/app.php".
Replaced the 'compiled' path in "config/view.php".
Added queue driver configuration in "config/queue.php".
Added Cloud SQL driver configuration in "config/database.php".
Added GAE filesystem driver configuration in "config/filesystems.php".
                                                                               
  [ErrorException]                                                             
  file_get_contents(/Users/ardalan/Documents/Projects/snow/storage/framework/  
  config.php): failed to open stream: No such file or directory                
                                                                     
```

Do you have any idea what's causing this?

**Comment by ardalann** [comment] 2015-04-10 20:40
I change this line in Setup/Configurator.php:
```php
$this->processFile($cached_config_php, ['fixCachedConfig']);
```
to:
```php
if ( file_exists($cached_config_php) ) $this->processFile($cached_config_php, ['fixCachedConfig']);
```
and it fixed the error.

I followed all the Optimization instructions in readme.
It reduced load times from 1000-2500ms to 500-1000ms (had one or two 380ms as well as 2500ms)

It's better but I expected much more from Laravel and GAE. Do you think it's the best load time we can get, even though I haven't even started developing the app yet?

**Comment by mattbucci** [comment] 2015-04-10 20:42
@ardalann you can try running a trace through the Google API Dashboard and see what's casuing the delays if anything

**Comment by ardalann** [comment] 2015-04-10 20:52
Thanks @mattbucci . This is my first experience with GAE and I didn't know that.
The delay is caused by four /urlfetch.Fetch requests to the GCS bucket:
```
/urlfetch.Fetch HEAD https://my-bucket123.storage.googleapis.com/storage returns http status code 404
/urlfetch.Fetch GET https://my-bucket123.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage returns 200
/urlfetch.Fetch HEAD https://my-bucket123.storage.googleapis.com/storage/framework/down returns 404
/urlfetch.Fetch GET https://my-bucket123.storage.googleapis.com/?delimiter=%2F&max-keys=1000&prefix=storage%2Fframework%2Fdown returns 200
```

So apparently, even though I've added this:
```
COMPILED_PATH = cachefs://framework/views
GAE_CACHE_SERVICES_FILE = true
GAE_CACHE_CONFIG_FILE = true
GAE_CACHE_ROUTES_FILE = true
GAE_SKIP_GCS_INIT = true
```
And removed ```FILESYSTEM=gae```, Laravel is still trying to access GCS.

**Comment by ardalann** [comment] 2015-04-10 21:48
I thought it could be an issue with env variables. So I went into ```framework/src/Illuminate/Foundations/helpers.php``` and in the ```env``` function added this:
```php
cho 'APP_ENV:'.print_r(getenv('APP_ENV'),1)."---";
$value = getenv($key);
echo $key.':'.print_r($value,1)."\n";
```
Check out the output!
```
APP_ENV:---GAE_CACHE_CONFIG_FILE:
APP_ENV:---GAE_CACHE_ROUTES_FILE:
APP_ENV:---GAE_SKIP_GCS_INIT:
APP_ENV:production---APP_ENV:production
APP_ENV:production---GAE_CACHE_CONFIG_FILE:true
APP_ENV:production---APP_DEBUG:false
...
```
It seems like all the env vars are being returned empty at the beginning. Any idea why?

**Comment by ardalann** [comment] 2015-04-10 22:08
Env variables are set in ```Dotenv::setEnvironmentVariable()``` method. Those cache variables are used before that method is called.
I moved those variables from ```.env``` to ```app.yamp```:
```
env_variables:
        GAE_CACHE_SERVICES_FILE: true
        GAE_CACHE_CONFIG_FILE: true
        GAE_CACHE_ROUTES_FILE: true
        GAE_SKIP_GCS_INIT: true
```
Now those first 3 env() calls return the correct value, however, it removed only the first 2 ```/urlfetch.Fetch``` request out of 4 I listed before. Now I'm trying to figure out why it's requesting ```/storage/framework/down```

**Comment by mattbucci** [comment] 2015-04-10 22:09
That sounds like a good call. Most people say to put the ENV variables into your apache config in production so i guess app.yaml makes a good substitute

**Comment by mattbucci** [comment] 2015-04-10 22:37
This is probably where it's getting called, but idk why. the /framework/down file just checks to see if the application is in maintenance mode


![screen shot 2015-04-10 at 3 36 41 pm](https://cloud.githubusercontent.com/assets/3284147/7098585/6c63fffa-df97-11e4-8315-421f862605a8.jpg)

**Comment by mattbucci** [comment] 2015-04-10 22:43
try adding this to the GaeSupportL5\Application class and see if it goes away

/**
	 * Determine if the application is currently down for maintenance.
	 *
	 * @return bool
	 */
	public function isDownForMaintenance()
	{
		return env('MaintenanceMode', false);
	}

**Comment by ardalann** [comment] 2015-04-10 22:48
Yes, you're right. I was able to disable it by commenting out the first middleware in ```/app/Http/Kernel.php``` : ```'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode'```

Now, page load times are usually between 250 - 650 ms (150-350ms based on Google traces). Still not as good as what I expected.

In the traces I can only see there's about 20 Memcache requests and each one takes about 1ms. Doesn't explain it.

**Comment by shpasser** [comment] 2015-04-11 18:46
Thanks for the report on `$cached_config_php`, will be fixed shortly.

As for the environment thing, something here seems to be wrong, because the only place in code requesting the `GAE_CACHE_CONFIG_FILE` variable is called from the constructor of the `Application` class, meaning it should happen only once. I will need to investigate this.

As for the rest of the time spent (not the Memcache requests of course) I would say it is partially spent on reading files from the read-only file system(where the static files are). We could simply measure the load times of static files of different sizes on the read-only filesystem(`file_get_contents`).

As for `CheckForMaintenanceMode`, will have to think about something that can replace the current Laravel's solution. Anyway persistency here is required in order to determine whether the app is in maintenance mode.

**Comment by shpasser** [comment] 2015-04-11 19:37
It looks like the best alternative for now is using `app.yaml` for the optimization related environment variables like @ardalann suggested. I see that I actually used `GAE_CACHE_CONFIG_FILE` more than once, so nothing is wrong here, not including my wrong assumption about when the environment initialization takes place.

**Comment by shpasser** [comment] 2015-04-12 09:59
I performed some more tests and it turns out that some of the changes made lately to `laravel/laravel` and `laravel/framework` may affect the proper functioning of GaeSupportL5 package. I will submit an update shortly. Additional changes have to be applied in order to simplify the use of `php artisan gae:setup` command.

As for now the correct sequence of deployment with optimized `config.php`, `routes.php` and `compiled.php` files would be:

1. Run `php artisan gae:setup` with all the desired options.
2. Add the optimization enabling options to the generated `app.yaml` and `.env.production` files.
3. Replace `.env` file with `.env.production` file.
4. Generate optimized `config.php`, `routes.php` and `compiled.php` files.
5. Run `php artisan gae:setup your-app-id` to prepare `config.php` for deployment.
6. Deploy the app by running `appcfg.py update ./` from your app folder.

BTW, use of `compiled.php` (generated with `php artisan optimize`) should spare some more time.

**Comment by shpasser** [comment] 2015-04-16 05:27
Pushed another update. Now config cache is generated automatically using the right environment. 
No need for workarounds, the deployment sequence is according to the readme file:

1. Run `php artisan gae:setup` with all the desired options.
2. Add the optimization enabling options to the generated `app.yaml` and `.env.production` files.
3. Replace `.env` file with `.env.production` file.
4. Generate optimized `routes.php` and `compiled.php` files.
5. Deploy the app by running `appcfg.py update ./` from your app folder.

**Comment by mmikulski** [comment] 2015-04-16 09:04
Have you tried playing with idle instances setting in Google App Engine?
https://cloud.google.com/appengine/docs/php/modules/#PHP_Instance_scaling_and_class

I haven't tried yet but I'm trying to wrap my head around it.
From what I understand every request gets into pending queue before it is forwarded to an instance.
Instances are created to respond to requests which explains a lag in comparison to normal server.
There's a possiblity to setup idle instances but this comes with a cost of running them.

**Comment by iog3** [comment] 2015-04-16 09:06
@mmikulski this refers to the amount of instances waiting for traffic, as there is a delay to spin up more, when you hit a GAE app when there are no instances the request takes around 15 seconds

**Comment by mmikulski** [comment] 2015-04-16 11:15
@iog3 I understand that.
In addition to that there's minimum pending latency which decides to start new or wait for existing one.
I wonder if adjusting those settings could improve response time.
Waiting for existing instance could be often more efficient then starting new one.

**Comment by mattbucci** [comment] 2015-04-16 18:05
@mmikulski I don't think that will effect it. It only switches to a new instance if the latency to an existing instance is too high, if you check your traces/instances page you can confirm that it's routing to an existing instance, but the latency is likely still around 250ms. This could be due to disk latency or other issues. I'll see if I can figure anything out about it today. But I'm guessing we're on the lower end of what's possible

**Comment by shpasser** [comment] 2015-04-16 18:31
I agree with @mattbucci. This feature seems to be about scalability and prices tradeoffs, while we are trying to improve average application request latency.

**Comment by shpasser** [comment] 2015-04-16 21:58
I think it is a time to add another stable version(tag).

Any comments?

**Comment by mmikulski** [comment] 2015-04-18 08:45
@mattbucci Thanks for the explanation.
I was playing a little bit with different settings but without luck.

**Comment by mattbucci** [comment] 2015-04-21 03:12
@shpasser @mmikulski  Just wanted to update that with the check for maintenance middleware disabled   and dedicated memcache enabled I'm getting some great performance. 
![screen shot 2015-04-20 at 8 06 05 pm 1](https://cloud.githubusercontent.com/assets/3284147/7244997/00937328-e799-11e4-99ef-e564598195c5.jpg)

To increase performance any more I'd have to look into what's being done prior to this memset
![screen shot 2015-04-20 at 8 06 30 pm](https://cloud.githubusercontent.com/assets/3284147/7244998/00957966-e799-11e4-8372-7d5acc7135c7.jpg)

but this looks like it's mostly application side, we're now matching the performance of the linode server at the top of this thread, any additional performance to be gained is minimal
![screen shot 2015-04-20 at 8 12 16 pm](https://cloud.githubusercontent.com/assets/3284147/7245040/948f35bc-e799-11e4-800b-55a3a4de3337.jpg)

**Comment by ardalann** [comment] 2015-04-21 04:24
Hey guys, I heard about <a href="http://lumen.laravel.com/">Lumen</a> a couple of hours ago.
On my local machine, a fresh install of Lumen loaded in 16ms.  (Laravel in 70-90ms)
Setting it up on GAE was a breeze! and without any optimizations, page load time was mostly around 100-130ms (My Laravel 5 setup with all the optimizations was loading in 200-500ms).
Have you thought about supporting Lumen instead of L5? It makes more sense since most people who want to use Laravel on GAE are after speed and scalability and that is what Lumen's for.

**Comment by shpasser** [comment] 2015-04-21 09:23
As I see it, the only problem of Lumen as of now is its maturity.
But it is built upon Laravel 5 base and concepts, meaning it is possible that it will become mature very quickly.

I think it is a really good idea.

**Comment by shpasser** [comment] 2015-05-04 06:25
Hello All,
Now we have a new tag 1.2 (stable).
In near future I'm planning to adapt the package for Lumen.
I would like to close the issue. In case of any objections please let me know,
otherwise it will be closed in 3 days.

**Closed** 2015-05-08 09:09 UTC

**Comment by shpasser** [comment] 2015-06-06 19:29
GAE support package for Lumen is out. Not stable yet.
https://packagist.org/packages/shpasser/gae-support-lumen
